### ISSUE TITLE
Suggestion for submodule address change

### ISSUE THREAD

**Issue by yoonc5536** [lawrenceccheung/amrwind-frontend#4]
I'm suggesting to use this line into "https" protocol to skip ssh key authentication if this repo is intended for public.

https://github.com/lawrenceccheung/amrwind-frontend/blob/31fadca1081dcd0d3a863f511e797afe508e485f/.gitmodules#L3

**Comment by lawrenceccheung** [comment]
Thanks, I just updated the gitmodules url.

Lawrence
